//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject1
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;


    [DeploymentItem("..\\webandloadtestproject1\\datasource.csv", "..\\webandloadtestproject1")]
    [DataSource("DataSource1", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\..\\webandloadtestproject1\\datasource.csv", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "datasource#csv")]
    [DataBinding("DataSource1", "datasource#csv", "abc", "DataSource1.datasource#csv.abc")]
    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.Context.Add("webserver", "localhost/index.html");
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("http://localhost/");
            request1.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request1.QueryStringParameters.Add("p", this.Context["DataSource1.datasource#csv.abc"].ToString());
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest(("http://" + this.Context["webserver"].ToString()));
            request2.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request2;
            request2 = null;
        }
    }
}
